// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Persimmon.Model.Interfaces")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: GuidAttribute("4f501257-f3ad-4bfc-b8f0-1d50330a554d")]
[assembly: AssemblyProductAttribute("Persimmon.Model.Interfaces")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
